import "./components/header.js";
import "./components/footer.js";
import "./components/card.js";
import "./pages/home.js";
import "./pages/gallery.js";
import "./pages/direction.js";
import "./pages/form.js";
import "./pages/team.js";
import "./router/router.js";
